// <auto-generated />
using Laba3.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Laba3.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221208185040_InitialCreate2")]
    partial class InitialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Laba3.Dal.Entities.Airline", b =>
                {
                    b.Property<string>("Airline_Id")
                        .HasColumnType("text");

                    b.Property<string>("Company_Name")
                        .HasColumnType("text");

                    b.HasKey("Airline_Id");

                    b.ToTable("Airline");
                });

            modelBuilder.Entity("Laba3.Dal.Entities.Passenger", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("First_Name")
                        .HasColumnType("text");

                    b.Property<string>("Last_Name")
                        .HasColumnType("text");

                    b.Property<string>("Passport_Number")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Passenger");
                });

            modelBuilder.Entity("Laba3.Dal.Entities.Ticket", b =>
                {
                    b.Property<string>("Ticket_Id")
                        .HasColumnType("text");

                    b.Property<string>("Airline_Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Flight_Date")
                        .HasColumnType("text");

                    b.Property<string>("Passenger_Id")
                        .HasColumnType("text");

                    b.HasKey("Ticket_Id");

                    b.HasIndex("Airline_Id");

                    b.HasIndex("Passenger_Id");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Laba3.Dal.Entities.Ticket", b =>
                {
                    b.HasOne("Laba3.Dal.Entities.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("Airline_Id");

                    b.HasOne("Laba3.Dal.Entities.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("Passenger_Id");

                    b.Navigation("Airline");

                    b.Navigation("Passenger");
                });
#pragma warning restore 612, 618
        }
    }
}
